- name: install mysql
  yum: name={{ item }} state=latest
  with_items:
    - mysql-community-server
    - MySQL-python
- name: copy sqlfile
  copy: "src={{ mysql_sqlfile }} dest=/home/vagrant/"
- name: copy my.cnf
  copy: "src=my.cnf dest=/etc/"
- name: copy my.cnf to root
  copy: src=my.cnf dest=/root/.my.cnf owner=root mode=0600
- name: copy timezone sql
  copy: src=setup-timezone.sql dest=/home/vagrant/
- name: start mysql and enabled
  service: name=mysqld state=started enabled=yes
- name: create user
  mysql_user: "name={{ mysql_userid }} password={{ mysql_passwd }} host={{ item }} priv={{ db_name }}.*:ALL,GRANT state=present"
  with_items:
    - localhost
    - 192.168.0.%
- name: create database
  mysql_db: "name={{ db_name }} state=present"
- name: initialize table
  shell: "/usr/bin/mysql -u {{ mysql_userid }} -p{{ mysql_passwd }} {{ db_name }} < {{ mysql_sqlfile }}"
- name: add timezone info
  shell: /usr/bin/mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
- name: set JST timezone
  shell: /usr/bin/mysql -u root mysql < setup-timezone.sql
