- name: copy phpinfo
  copy: "src=phpinfo.php dest=\"{{ wwwroot }}\" owner=vagrant"
- name: install php
  yum: pkg={{ item }} state=latest enablerepo=remi,remi-php56
  with_items:
    - php
    - php-devel
    - php-mbstring
    - php-mysql
- name: install composer
  shell: /usr/bin/curl -s http://getcomposer.org/installer | php && mv -f composer.phar /usr/bin/composer
  notify: restart apache
